In [1]:
import numpy as np

## Numpy vs List

In [7]:
x = [1,2,3]
y = [4,5,6]
x*y

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x*y

array([ 4, 10, 18])

In [9]:
just_a_list = [1,2,3]
just_a_list

[1, 2, 3]

In [10]:
np.array(just_a_list)

array([1, 2, 3])

In [11]:
just_a_matrix = [[1,2,3],[4,5,6],[7,8,9]]
just_a_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(just_a_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange

In [47]:
# 序列
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
#step size of 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Zeros and Ones

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# 等差数列 [0, 10]间取3个数
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [35]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## eye

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

### rand

In [38]:
# 均匀分布 over [0, 1).
np.random.rand(2)

array([0.90389089, 0.3510208 ])

In [39]:
np.random.rand(3,3)

array([[0.45309538, 0.48363267, 0.6003094 ],
       [0.94040643, 0.63503818, 0.964836  ],
       [0.82064542, 0.39588051, 0.03267162]])

### randn

In [40]:
# 标准正态分布，高斯分布
np.random.randn(2)

array([1.12788163, 0.01070903])

In [42]:
np.random.randn(3, 4)

array([[-0.15585462,  0.80631053, -0.33503907, -0.22703332],
       [ 0.41523201, -0.56875191, -0.62329862, -0.54037772],
       [ 2.78599847,  0.65488879, -0.51687345, -0.06341576]])

### randint

In [45]:
np.random.randint(1, 100)

16

In [46]:
#generates 10 random
#integers between 1 to 100
np.random.randint(1, 100, 10)

array([66, 98, 31, 76, 62, 57, 91, 86, 67,  8])

## Array Attributes and Methods

### Reshape

In [49]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
arr.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### max, min, argmax, argmin

In [59]:
random_arr = np.random.randint(0, 50, 10)
random_arr

array([ 6,  0, 13, 12, 10,  7,  7,  7, 33, 38])

In [60]:
random_arr.max(), random_arr.min()

(38, 0, 9, 1)

In [63]:
# 取最值时，对应的下标/索引
random_arr.argmax(), random_arr.argmin()

(9, 1)

### Shape

In [64]:
arr.shape

(16,)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [66]:
arr.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [67]:
arr.shape

(16,)

In [69]:
arr.reshape(16, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [70]:
arr.reshape(16, 1).shape

(16, 1)

### dtype

In [71]:
arr.dtype

dtype('int64')

## NumPy Indexing and Selection

In [72]:
arr[5]

5

In [73]:
arr[1:5]

array([1, 2, 3, 4])

In [74]:
arr[-5:]

array([11, 12, 13, 14, 15])

## Broadcasting

In [75]:
arr[0:5] = 99

In [76]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [82]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [83]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
a = [[1,2,3],[4,5,6]]
np_a = np.array(a)
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np_a.shape

(2, 3)

In [91]:
b = [100,200,300]
np_b = np.array(b)
np_b

array([100, 200, 300])

In [93]:
np_b.shape

(3,)

In [94]:
np_b_reshape = np_b.reshape(1, 3)

In [95]:
np_b_reshape.shape

(1, 3)

In [96]:
np_a + np_b_reshape

array([[101, 202, 303],
       [104, 205, 306]])

In [97]:
np.array([[100,200,300],[100,200,300]])

array([[100, 200, 300],
       [100, 200, 300]])

## Indexing a 2D array (matrices)

In [99]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr_2d[2]

array([7, 8, 9])

In [104]:
arr_2d[1][0]

4

In [105]:
arr_2d[1, 0]

4

In [106]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [108]:
arr_2d[2]

array([7, 8, 9])

## Selection

In [111]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [113]:
bool_arr = arr1 > 5

In [114]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [115]:
arr1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [116]:
arr1[arr1 > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## NumPy Operations

### Arithmetic

In [119]:
arr2 = np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [120]:
arr2 * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [121]:
arr2 / arr2

/Users/mgbook/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

> Another warning, but not an error. Value will be replaced with infinity.

In [122]:
1 / arr2

/Users/mgbook/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [123]:
arr2 ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

### Universal Array Functions

In [125]:
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [126]:
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [127]:
np.max(arr2)

9

In [128]:
np.sin(arr2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [129]:
np.log(arr2)

/Users/mgbook/.pyenv/versions/3.6.4rc1/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Vectorization 
向量化计算

In [130]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic= time.time()
c = np.dot(a,b) #dot product of two vectors
toc = time.time()
print("Time taken in vectorized version: "+str(1000 * (toc - tic))+" ms")

Time taken in vectorized version: 3.097057342529297 ms


In [131]:
c = 0
tic = time.time()
for i in range(1000000):
  c += a[i] * b[i]
toc = time.time()
print("Time taken in for loop version: "+str(1000 *(toc - tic)) + " ms")

Time taken in for loop version: 589.8408889770508 ms
